<script setup lang="ts">
import { computed, getCurrentInstance, onMounted, reactive, ref } from 'vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import { useCategoryStore } from '../stores/categories'
import { useTransactionStore } from '../stores/transactions'
import type { Category, Transaction } from '../types'

const toast = getCurrentInstance()!.appContext.config.globalProperties.$toast as { success: (message: string) => void }
const categoryStore = useCategoryStore(); const transactionStore = useTransactionStore(); const categories = ref<Category[]>([]); const transactions = ref<Transaction[]>([]); const loading = ref(true); const deleting = ref<Category | null>(null)
const form = reactive({ name: '' }); const errors = reactive<Record<string, string>>({}); const touched = ref(false)
const custom = computed(() => categories.value.filter((category) => category.type === 'custom')); const predefined = computed(() => categories.value.filter((category) => category.type === 'predefined'))
onMounted(async () => { [categories.value, transactions.value] = await Promise.all([categoryStore.getAll(), transactionStore.getAll()]); loading.value = false })
function usage(category: Category) { return transactions.value.filter((transaction) => transaction.category === category.name).length }
function validate() { errors.name = ''; if (!form.name.trim()) errors.name = 'Enter a category name.'; else if (categories.value.some((category) => category.name.toLowerCase() === form.name.trim().toLowerCase())) errors.name = 'This category already exists.'; if (!errors.name) delete errors.name; return !errors.name }
async function add() { touched.value = true; if (!validate()) return; await categoryStore.create(form.name.trim()); categories.value = await categoryStore.getAll(); form.name = ''; touched.value = false; toast.success('Custom category added.') }
async function confirmDelete() { if (!deleting.value) return; await categoryStore.remove(deleting.value.id); categories.value = await categoryStore.getAll(); deleting.value = null; toast.success('Custom category deleted.') }
</script>

<template><section class="mx-auto max-w-5xl p-5 md:p-8 lg:p-10"><div><h1 class="text-3xl font-bold">Categories</h1><p class="mt-1 text-sm text-muted">Organize your spending with categories.</p></div><div v-if="loading" class="mt-8 h-64 animate-pulse rounded-card bg-slate-200" /><template v-else><div class="mt-8 grid gap-6 lg:grid-cols-2"><article class="rounded-card border border-border bg-white p-6 shadow-card"><h2 class="text-lg font-bold">Add custom category</h2><p class="mt-1 text-sm text-muted">Create categories that fit your life.</p><form class="mt-5 flex gap-3" @submit.prevent="add"><input v-model="form.name" class="form-input mt-0" placeholder="e.g. Pets" @blur="touched = true; validate()"><button type="submit" class="btn-primary" :disabled="!form.name.trim()">Add</button></form><p v-if="touched && errors.name" class="mt-2 text-xs text-expense">{{ errors.name }}</p></article><article class="rounded-card border border-border bg-white p-6 shadow-card"><h2 class="text-lg font-bold">Predefined categories</h2><div class="mt-5 flex flex-wrap gap-2"><span v-for="category in predefined" :key="category.id" class="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-medium text-primary">{{ category.name }}</span></div></article></div><article class="mt-6 rounded-card border border-border bg-white p-6 shadow-card"><h2 class="text-lg font-bold">Custom categories</h2><div v-if="custom.length" class="mt-4 divide-y divide-border"><div v-for="category in custom" :key="category.id" class="flex items-center justify-between py-4"><div><p class="font-semibold">{{ category.name }}</p><p class="text-xs text-muted">Used by {{ usage(category) }} transaction{{ usage(category) === 1 ? '' : 's' }}</p></div><button class="text-sm font-semibold" :class="usage(category) ? 'cursor-not-allowed text-slate-300' : 'text-expense'" :disabled="Boolean(usage(category))" @click="deleting = category">Delete</button></div></div><p v-else class="py-8 text-center text-sm text-muted">No custom categories yet.</p></article></template><ConfirmDialog :open="Boolean(deleting)" title="Delete category?" message="This custom category will be permanently removed." @cancel="deleting = null" @confirm="confirmDelete" /></section></template>
