<script setup lang="ts">
import { useRouter } from 'vue-router'
import { computed, getCurrentInstance, onMounted, reactive, ref } from 'vue'
import { useCategoryStore } from '../stores/categories'
import type { Category, TransactionInput, TransactionType } from '../types'

const toast = getCurrentInstance()!.appContext.config.globalProperties.$toast as { error: (message: string) => void }
const props = defineProps<{ initial?: TransactionInput; submitLabel: string }>()
const emit = defineEmits<{ submit: [input: TransactionInput] }>()
const router = useRouter(); const categoryStore = useCategoryStore(); const categories = ref<Category[]>([])
const form = reactive<TransactionInput>({ amount: props.initial?.amount ?? 0, type: props.initial?.type ?? 'Expense', category: props.initial?.category ?? '', date: props.initial?.date ?? new Date().toISOString().slice(0, 10), description: props.initial?.description ?? '' })
const errors = reactive<Record<string, string>>({}); const touched = reactive<Record<string, boolean>>({})
const isValid = computed(() => form.amount > 0 && Boolean(form.category) && Boolean(form.date) && Boolean(form.description.trim()))
onMounted(async () => { categories.value = await categoryStore.getAll() })
function validate() { Object.keys(errors).forEach((key) => delete errors[key]); if (!Number.isFinite(Number(form.amount)) || form.amount <= 0) errors.amount = 'Enter a positive amount.'; if (!form.category) errors.category = 'Choose a category.'; if (!form.date) errors.date = 'Choose a date.'; if (!form.description.trim()) errors.description = 'Enter a description.'; return Object.keys(errors).length === 0 }
function markTouched(field: string) { touched[field] = true; validate() }
function submitForm() { Object.assign(touched, { amount: true, category: true, date: true, description: true }); if (!validate()) { toast.error('Please correct the highlighted fields.'); return }; emit('submit', { ...form, amount: Number(form.amount), description: form.description.trim() }) }
</script>

<template><form class="rounded-card border border-border bg-white p-6 shadow-card" @submit.prevent="submitForm"><div class="grid gap-6 md:grid-cols-2"><fieldset><legend class="text-sm font-semibold">Transaction type</legend><div class="mt-2 flex rounded-lg bg-slate-100 p-1"><button v-for="type in ['Expense', 'Income'] as TransactionType[]" :key="type" type="button" :class="form.type === type ? (type === 'Income' ? 'bg-income text-white' : 'bg-expense text-white') : 'text-muted'" class="flex-1 rounded-md px-3 py-2 text-sm font-semibold" @click="form.type = type">{{ type }}</button></div></fieldset><label class="text-sm font-semibold">Amount<input v-model.number="form.amount" type="number" min="0.01" step="0.01" class="form-input" placeholder="0.00" @blur="markTouched('amount')"><p v-if="touched.amount && errors.amount" class="mt-1 text-xs text-expense">{{ errors.amount }}</p><p v-else class="mt-1 text-xs text-muted">Enter a positive amount.</p></label><label class="text-sm font-semibold">Category<select v-model="form.category" class="form-input" @blur="markTouched('category')"><option disabled value="">Select category</option><option v-for="category in categories" :key="category.id" :value="category.name">{{ category.name }}</option><option v-if="form.type === 'Income'" value="Salary">Salary</option><option v-if="form.type === 'Income'" value="Freelance">Freelance</option></select><p v-if="touched.category && errors.category" class="mt-1 text-xs text-expense">{{ errors.category }}</p></label><label class="text-sm font-semibold">Date<input v-model="form.date" type="date" class="form-input" @blur="markTouched('date')"><p v-if="touched.date && errors.date" class="mt-1 text-xs text-expense">{{ errors.date }}</p></label><label class="text-sm font-semibold md:col-span-2">Description<input v-model="form.description" class="form-input" placeholder="What was this for?" @blur="markTouched('description')"><p v-if="touched.description && errors.description" class="mt-1 text-xs text-expense">{{ errors.description }}</p></label></div><div class="mt-8 flex justify-end gap-3"><button type="button" class="btn-secondary" @click="router.push('/transactions')">Cancel</button><button type="submit" class="btn-primary" :disabled="!isValid">{{ submitLabel }}</button></div></form></template>
